### ISSUE TITLE
plugin settings

### ISSUE THREAD

**Issue by esdee-git** [jprante/elasticsearch-plugin-bundle#33]
Hi
I try to add some custom settings for some of the plugins in the bundle, but can't understand how settings work.
For example to add custom setting to Decompounder, I go to DecompoundTokenFilterFactory and try to read my custom setting in createDecompounder(Settings settings).
But 'settings' always comes empty!?
What am I getting wrong?
Also if I add an existing property, e.g. subwords_only: true, it seems to be read by the plugin, but still the method createDecompounder the settings object is empty (I'm checking with settings.toDelimitedString)

Thanks for any hints!

**Comment by jprante** [comment]
It's not empty in `DecompoundTokenFilterTests`. Printing the settings give

```
[18:40:11,328][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][main] settings = type=decompound 
[18:40:11,369][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][main] settings = subwords_only=true type=decompound 
[18:40:11,401][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][main] settings = respect_keywords=true type=decompound 
[18:40:11,409][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][main] settings = respect_keywords=false type=decompound 
[18:40:11,704][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][main] settings = index.version.created=5030099 
[18:40:12,277][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][main] settings = type=decompound 
[18:40:12,295][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][main] settings = index.version.created=5030099 
```

See the test resource `src/test/resources/org/xbib/elasticsearch/index/analysis/decompound/patricia/keywords_analysis.json` how to define settings.

**Comment by esdee-git** [comment]
Jörg, thanks for helping with this, but I'm still puzzled:
i'm runnning this:
`./gradlew test -d --tests org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterTests`

in the logs you can see the output of settings.toDelimitedString(',') is empty:
```
10:51:18.920 [DEBUG] [TestEventLogger] org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterTests STARTED
..
[TestEventLogger] org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterTests > testWithSubwordsOnly STANDARD_OUT
..
10:51:21.825 [DEBUG] [TestEventLogger]     [10:51:21,824][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][Test worker] decompunder settings: 
10:51:21.930 [DEBUG] [TestEventLogger]     [10:51:21,928][INFO ][org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterFactory][Test worker] decompunder subwords setting:
```

in keywords_analysis.json i'm setting "subwords_only" : false, and the tests fail as expected:
```
10:51:24.061 [DEBUG] [TestEventLogger] org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterTests > testWithSubwordsOnly FAILED
10:51:24.062 [DEBUG] [TestEventLogger]     org.junit.ComparisonFailure: expected:<Da[]> but was:<Da[s]>
10:51:24.062 [DEBUG] [TestEventLogger]         at org.junit.Assert.assertEquals(Assert.java:115)
10:51:24.062 [DEBUG] [TestEventLogger]         at org.junit.Assert.assertEquals(Assert.java:144)
10:51:24.062 [DEBUG] [TestEventLogger]         at org.xbib.elasticsearch.index.analysis.decompound.patricia.DecompoundTokenFilterTests.assertSimpleTSOutput(DecompoundTokenFilterTests.java:90)
```

so my code is executed and yet settings is empty, unlike in your example.
i'm tied to ES&bundle 5.2.2, could this have anything to do with this?

**Comment by esdee-git** [comment]
Thanks, Jörg! Found the problem in my code..
