### ISSUE TITLE
installing for elasticsearch 6.5

### ISSUE THREAD

**Issue by WestleyArgentum** [jprante/elasticsearch-plugin-bundle#38]
Hey, thanks for this bundle, it looks great! I'm a little confused how to install for elasticsearch version 6.x though... 

I see the latest version tagged here on github is 6.3.2.2, but when I run

```
./bin/elasticsearch-plugin install https://github.com/jprante/elasticsearch-plugin-bundle/archive/6.3.2.2.zip
```

I get errors like 

```
$ sudo bin/elasticsearch-plugin install https://github.com/jprante/elasticsearch-plugin-bundle/archive/6.3.2.2.zip
-> Downloading https://github.com/jprante/elasticsearch-plugin-bundle/archive/6.3.2.2.zip
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/.installing-8072144053884413337/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:713)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:792)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:775)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

I noticed that in the readme you have instructions for older version that use links to other sites like `http://search.maven.org`... Is there something different about those bundles? Or maybe I'm missing something more basic – I'm fairly new to elasticsearch and this is my first time setting it up from scratch.

**Comment by SakulK** [comment]
@WestleyArgentum I think you are using wrong a wrong zip to install the plugin, try http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/6.3.2.1/elasticsearch-plugin-bundle-6.3.2.1.zip

My question for @jprante: is a version for 6.5 planned/worked on already or not in the near future?

**Comment by dinamic** [comment]
ping @jprante
